version: "3"

networks:
  shared:
    external: true

services:
  redis:
    image: redis:7.4
    hostname: my-redis
    container_name: my-redis
    volumes:
      - ./dev-env/redis/volumes/data:/data
    ports:
      - 6379:6379
    networks:
      - shared

