spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

datago:
  auth-key: 123

my:
  opensearch:
    uris: localhost:9200

